return {
  { import = 'plugins.spec.autopairs' },
  { import = 'plugins.spec.copilot' },
  { import = 'plugins.spec.copilot-cmp' },
  { import = 'plugins.spec.fterm' },
  { import = 'plugins.spec.gitsigns' },
  { import = 'plugins.spec.lspkind' },
  { import = 'plugins.spec.lsp-zero' },
  { import = 'plugins.spec.mason' },
  { import = 'plugins.spec.neo-tree' },
  { import = 'plugins.spec.nvim-cmp' },
  { import = 'plugins.spec.nvim-lspconfig' },
  -- { import = 'plugins.spec.nvim-tree' },
  { import = 'plugins.spec.nvim-treesitter' },
  { import = 'plugins.spec.nvim-web-devicons' },
  { import = 'plugins.spec.plenary' },
  { import = 'plugins.spec.rustaceanvim' },
  { import = 'plugins.spec.telescope-fzf-native' },
  { import = 'plugins.spec.telescope' },
  { import = 'plugins.spec.todo-comments' },
  { import = 'plugins.spec.ufo' },
  { import = 'plugins.spec.which-key' },
  { import = 'plugins.theme.onedark' },
}
